### ISSUE TITLE
bad dependency

### ISSUE THREAD

**Issue by jeffclay** [negativo17/spotify-ripper#1]
dnf install spotify-ripper
Last metadata expiration check: 0:05:06 ago on Sat 11 Jul 2020 12:42:21 AM CDT.
Error: 
 Problem: conflicting requests
  - nothing provides python3.8dist(schedule) >= 0.3.1 needed by spotify-ripper-2.13-1.fc32.noarch
  - nothing provides python3.8dist(schedule) >= 0.3.1 needed by spotify-ripper-2.14-1.fc32.noarch

**Comment by scaronni** [comment]
Oops, forgot to push the `python-schedule` package. It will be online in ~30 minutes.
