### ISSUE TITLE
unresolved dependency 

### ISSUE THREAD

**Issue by HenryRc0** [negativo17/spotify-ripper#3]
Fedora36

**dnf install spotify-ripper**
Letzte Prüfung auf abgelaufene Metadaten: vor 1:08:45 am Di 14 Jun 2022 07:44:41.
Fehler: 
 Problem: widersprüchliche Anforderungen
  - nichts stellt python3.10dist(schedule) >= 0.3.1 bereit, das von spotify-ripper-2.18-1.fc36.noarch benötigt wird
(try to add '--skip-broken' to skip uninstallable packages)

**Comment by scaronni** [comment]
libspotify does not work anymore as of 16th of May 2022 unfortunately.
